### ISSUE TITLE
Not planer face out of range

### ISSUE THREAD

**Issue by mma1377** [helpsterTee/XBivine-Unity#1]
Thanks for your work. It is really genius to implement such a platform-independent importer tool. 
However, I faced a problem when the model had not planer faces. IfcImporterv2.cv indexes i0, i1, i2 of facNormals at line 292 which can be out of range. i0, i1, i2 are values of indices and it is obvious those can index out of range. I've checked json file created for these models and understood the count of normals is the same as indices so I've changed i0 to k, i1 to k+1, i2 to k3 and it worked.
I'm not sure I did the right thing and now I am importing the model correctly or not. Please inform me if you think I am wrong.
Thank you for your attention.

**Comment by helpsterTee** [comment]
Can you drop me the values for facNormals, i0,i1, and i2 in the crash case? I guess you're right, but I want to verify.

**Comment by mma1377** [comment]
![indices](https://user-images.githubusercontent.com/35420218/109123512-2cabff00-775f-11eb-9b57-6935be59a2a2.PNG)
In this case in the first iteration the value of i0, i1, i2 are 47, 37 46 while the length of faceNormal is 6

**Comment by helpsterTee** [comment]
Thanks, fixed in master :)

**Comment by mma1377** [comment]
lines 297, 298, 299 still index to i0, i1, i2 of facNormals

**Comment by helpsterTee** [comment]
Now okay?

**Comment by mma1377** [comment]
Thanks. Yes, now it is ok.
